version: '3'

networks:
  nexus:

services:

  nexus:
    image: sonatype/nexus3:3.2.1
    container_name: nexus
    ports:
    - 8081:8081
    - 5000:5000
    networks:
    - nexus

  nginx:
    build: .
    container_name: nginx_nexus
    ports:
    - 80:80
    - 443:443
    networks:
    - nexus



